version: '3.8'

services:
  myapp:
    build:
      context: ../../
      dockerfile: devops/docker/Dockerfile
    environment:
      - MY_ENV=dev
    ports:
      - 8080:8080
    volumes:
      - ../../application:/application
