name: Build, Test and Push Docker Image

on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - actions

env:
  IMAGE_NAME: ghcr.io/nurlanf/listen-and-display
  TAG: "1.0.0"
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Run Container and Test
        run: |
          docker run -d --name my-app -p 8080:8080 ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          sleep 10  # wait for the app to start
          response=$(curl http://localhost:8080/api?text=sometext)
          echo "Response: $response"
          if [[ "$response" == *"Received"* ]]; then
              echo "Test Passed"
          else
              echo "Test Failed"
              exit 1
          fi

      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/mytargetbranch'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: devops/docker/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
